# -*- coding: utf-8 -*-
"""BSvsBinomial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reT4E1gBhq25-lb53uBpvdOHBkhA5zba
"""

#@title Importing Libraries
import numpy as np
from scipy.stats import norm
import math
from math import log, sqrt, pi, exp
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timezone
import yfinance as yf

ticker = 'AAPL'
option = yf.Ticker(ticker)
option.options

#@title Getting the Call Dataset
# Picking a date from the above
date = '2024-09-20'

def fetch_options_data(ticker_symbol, date):
    ticker = yf.Ticker(ticker_symbol)
    options_data = ticker.option_chain(date)
    return options_data.calls, options_data.puts



calls, puts = fetch_options_data(ticker, date)
calls = pd.DataFrame(calls)
calls.head()

#@title Binomial Model
## define Cox_Ross_Rubinstein binomial model
def Cox_Ross_Rubinstein_Tree (S,K,T,r,sigma, Option_type, N = 100):

    # Underlying price (per share): S;
    # Strike price of the option (per share): K;
    # Time to maturity (years): T;
    # Continuously compounding risk-free interest rate: r;
    # Volatility: sigma;
    # Number of binomial steps: N;

        # The factor by which the price rises (assuming it rises) = u ;
        # The factor by which the price falls (assuming it falls) = d ;
        # The probability of a price rise = pu ;
        # The probability of a price fall = pd ;
        # discount rate = disc ;

    u=math.exp(sigma*math.sqrt(T/N));
    d=math.exp(-sigma*math.sqrt(T/N));
    pu=((math.exp(r*T/N))-d)/(u-d);
    pd=1-pu;
    disc=math.exp(-r*T/N);

    St = [0] * (N+1)
    C = [0] * (N+1)

    St[0]=S*d**N;

    for j in range(1, N+1):
        St[j] = St[j-1] * u/d;

    for j in range(1, N+1):
        if Option_type == 'P':
            C[j] = max(K-St[j],0);
        elif Option_type == 'C':
            C[j] = max(St[j]-K,0);

    for i in range(N, 0, -1):
        for j in range(0, i):
            C[j] = disc*(pu*C[j+1]+pd*C[j]);

    return C[0]

#@title Black-Scholes Model
# Underlying price (per share): S;
# Strike price of the option (per share): K;
# Time to maturity (years): T;
# Continuously compounding risk-free interest rate: r;
# Volatility: sigma;

## define two functions, d1 and d2 in Black-Scholes model
def d1(S,K,T,r,sigma):
    return(log(S/K)+(r+sigma**2/2.)*T)/sigma*sqrt(T)
def d2(S,K,T,r,sigma):
    return d1(S,K,T,r,sigma)-sigma*sqrt(T)

## define the call options price function
def bs_call(S,K,T,r,sigma):
    return S*norm.cdf(d1(S,K,T,r,sigma))-K*exp(-r*T)*norm.cdf(d2(S,K,T,r,sigma))

## define the put options price function
def bs_put(S,K,T,r,sigma):
    return K*exp(-r*T)-S+bs_call(S,K,T,r,sigma)

#@title Defining inputs for the models
def get_current_stock_price(ticker_symbol):
    stock = yf.Ticker(ticker_symbol)
    current_price = stock.history(period='1d')['Close'].iloc[-1]
    return current_price



def get_10yr_treasury_rate():
    # 10 year treasury ticker symbol
    treasury_ticker = "^TNX"

    now = datetime.now()
    ten_years_ago = now.replace(year=now.year - 10)

    treasury_data = yf.download(treasury_ticker, start=ten_years_ago, end=now)
    last_yield = treasury_data['Close'].iloc[-1]
    return last_yield



def get_date(date_str):
    # Assuming the date string is in the format 'YYYY-MM-DD'
    date_object = datetime.strptime(date_str, '%Y-%m-%d')

    current_date = datetime.now()
    years_difference = (date_object - current_date).days / 365.25
    return years_difference



def calculate_volatility(ticker):

    today = datetime.now()
    one_year_ago = today.replace(year=today.year-1)
    data = yf.download(ticker, start=one_year_ago, end=today)

    # Calculate daily returns
    data['Daily_Return'] = data['Adj Close'].pct_change()

    # std of daily returns
    daily_volatility = data['Daily_Return'].std()
    annualized_volatility = daily_volatility * np.sqrt(252)

    return annualized_volatility



S = get_current_stock_price(ticker)
r = get_10yr_treasury_rate()
t = get_date(date)
vol = calculate_volatility(ticker)

# Converting r to percentage
r = r / 100

print(f"Riskfree rate: {r}")
print(f"Years difference: {t}")
print(f"The current stock price of {ticker} is: {S}")
print(f"Stock price of {ticker}: {S}")

main_df = calls.copy()
columns_to_drop = ['lastTradeDate',  'volume', 'openInterest', 'contractSize', 'currency']
main_df.drop(columns=columns_to_drop, inplace=True)
main_df['bsmValuation'] = main_df.apply(lambda row: bs_call(S, row['strike'], t, r, vol), axis=1)
main_df['binValuation'] = main_df.apply(lambda row: Cox_Ross_Rubinstein_Tree(S, row['strike'], t, r, vol, 'C'), axis=1)
main_df.head(10)

#@title Visualising Result
# Calculate absolute errors
main_df['absErrorBS'] = np.abs(main_df['lastPrice'] - main_df['bsmValuation'])
main_df['absErrorBin'] = np.abs(main_df['lastPrice'] - main_df['binValuation'])

# Calculate mean absolute errors
mean_abs_error_bs = main_df['absErrorBS'].mean()
mean_abs_error_bin = main_df['absErrorBin'].mean()

print(f"Mean Absolute Error (Black-Scholes): {mean_abs_error_bs:.2f}")
print(f"Mean Absolute Error (Binomial): {mean_abs_error_bin:.2f}")

# Plot actual vs predicted prices
plt.figure(figsize=(14, 7))

plt.subplot(1, 2, 1)
plt.scatter(main_df['lastPrice'], main_df['bsmValuation'], color='blue', label='Black-Scholes', alpha=0.5)
plt.scatter(main_df['lastPrice'], main_df['binValuation'], color='red', label='Binomial', alpha=0.5)
plt.plot([main_df['lastPrice'].min(), main_df['lastPrice'].max()],
         [main_df['lastPrice'].min(), main_df['lastPrice'].max()],
         color='green', linestyle='--')
plt.xlabel('Actual Price')
plt.ylabel('Predicted Price')
plt.title('Actual vs Predicted Prices')
plt.legend()

# Plot error distributions
plt.subplot(1, 2, 2)
plt.hist(main_df['absErrorBS'], bins=20, alpha=0.5, label='Black-Scholes', color='blue')
plt.hist(main_df['absErrorBin'], bins=20, alpha=0.5, label='Binomial', color='red')
plt.xlabel('Absolute Error')
plt.ylabel('Frequency')
plt.title('Error Distribution')
plt.legend()

plt.tight_layout()
plt.show()

# @title Comparison of Valuation Models

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.scatter(main_df['bsmValuation'], main_df['binValuation'])
plt.xlabel('BSM Valuation')
plt.ylabel('Binomial Valuation')
_ = plt.title('Comparison of Valuation Models')

date = '2026-12-18'

def fetch_options_data(ticker_symbol, date):
    ticker = yf.Ticker(ticker_symbol)
    options_data = ticker.option_chain(date)
    return options_data.calls, options_data.puts



calls, puts = fetch_options_data(ticker, date)
puts = pd.DataFrame(puts)
puts.head()

main_df = puts.copy()
columns_to_drop = ['lastTradeDate', 'volume', 'openInterest', 'contractSize', 'currency']
main_df.drop(columns=columns_to_drop, inplace=True)
main_df['bsmValuation'] = main_df.apply(lambda row: bs_put(S, row['strike'], t, r, vol), axis=1)
main_df['binValuation'] = main_df.apply(lambda row: Cox_Ross_Rubinstein_Tree(S, row['strike'], t, r, vol, 'P'), axis=1)
main_df.head(10)