# -*- coding: utf-8 -*-
"""FinSearch_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-R9wtPatEyJmO8TGvFi4grELj21E8Hed
"""

# @title Importing Libraries
import pandas as pd
import numpy as np
from datetime import datetime
from scipy.stats import norm
import matplotlib.pyplot as plt

# @title Data Preprocessing
def clean_csv_file(input_file_path, output_file_path):
    with open(input_file_path, 'r') as file:
        lines = file.readlines()

    with open(output_file_path, 'w') as file:
        for line in lines:
            # Remove leading commas
            if line.startswith(','):
                line = line.lstrip(',')
            # Remove trailing commas
            if line.endswith(','):
                line = line.rstrip(',')
            file.write(line)

# @title Generating DataFrame
# Function to read and process the Nifty50 data file
def process_nifty50_data(file_path):

    df = pd.read_csv(file_path, skiprows=1)

    # Define the columns for CALLS and PUTS
    calls_columns = [
        'OI_CALL', 'CHNG IN OI_CALL', 'VOLUME_CALL', 'IV_CALL', 'LTP_CALL',
        'CHNG_CALL', 'BID QTY_CALL', 'BID_CALL', 'ASK_CALL', 'ASK QTY_CALL', 'STRIKE'
        ]
    puts_columns = [
        'BID QTY_PUT', 'BID_PUT', 'ASK_PUT', 'ASK QTY_PUT',
        'CHNG_PUT', 'LTP_PUT', 'IV_PUT', 'VOLUME_PUT', 'CHNG IN OI_PUT', 'OI_PUT', 'JK'
    ]

    # Assign the column names
    df.columns = calls_columns + puts_columns

    # Drop rows with '-' in any entry
    df.iloc[:, :-1] = df.iloc[:, :-1].replace('-', pd.NA)
    df.dropna(subset=df.columns[:-1], inplace=True)

    return df

# @title Black-Scholes Model
# Black-Scholes Model function
def black_scholes(S, K, T, r, sigma, option_type):
    d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)

    if option_type == "call":
        price = S * norm.cdf(d1, 0.0, 1.0) - K * np.exp(-r * T) * norm.cdf(d2, 0.0, 1.0)
    elif option_type == "put":
        price = K * np.exp(-r * T) * norm.cdf(-d2, 0.0, 1.0) - S * norm.cdf(-d1, 0.0, 1.0)

    return price

# @title Backtesting
# Backtesting function
def backtest_black_scholes(data, r, stock_price):
    results = []

    for index, row in data.iterrows():
        strike = float(row['STRIKE'].replace(',', ''))
        expiry_date = "2024-08-22"

        # Time to maturity
        T = (datetime.strptime(expiry_date, '%Y-%m-%d') - datetime.now()).days / 365.0

        # For Calls
        iv_call = float(row['IV_CALL'].replace(',', '')) / 100
        real_price_call = float(row['LTP_CALL'].replace(',', ''))
        bs_price_call = black_scholes(stock_price, strike, T, r, iv_call, option_type="call")
        error_call = abs(real_price_call - bs_price_call)

        results.append({
            'type': 'call',
            'strike': strike,
            'real_price': real_price_call,
            'bs_price': bs_price_call,
            'error': error_call
        })

        # For Puts
        iv_put = float(row['IV_PUT'].replace(',', '')) / 100
        real_price_put = float(row['LTP_PUT'].replace(',', ''))
        bs_price_put = black_scholes(stock_price, strike, T, r, iv_put, option_type="put")
        error_put = abs(real_price_put - bs_price_put)

        results.append({
            'type': 'put',
            'strike': strike,
            'real_price': real_price_put,
            'bs_price': bs_price_put,
            'error': error_put
        })

    results_df = pd.DataFrame(results)
    return results_df

# @title Main Function
if __name__ == "__main__":

    file_path = "/content/option-chain-ED-NIFTY-22-Aug-2024 (1).csv"  # Dataset
    r = 0.05
    stock_price = 24572.65  # Nifty50 current price

    cleaned_file_path = "cleaned_nifty50_data.csv"

    clean_csv_file(file_path, cleaned_file_path)
    nifty_data = process_nifty50_data(cleaned_file_path)

    # Backtest
    results_df = backtest_black_scholes(nifty_data, r, stock_price)
    print(results_df)

    # Evaluate performance
    mae_call = results_df[results_df['type'] == 'call']['error'].mean()
    mae_put = results_df[results_df['type'] == 'put']['error'].mean()
    print(f"Mean Absolute Error (MAE) for Calls: {mae_call}")
    print(f"Mean Absolute Error (MAE) for Puts: {mae_put}")

# @title Visualising Results
# Plot real price vs. calculated price for CALLS
plt.figure(figsize=(12, 6))
plt.plot(results_df[results_df['type'] == 'call']['real_price'], label='Real CALL Price')
plt.plot(results_df[results_df['type'] == 'call']['bs_price'], label='Calculated CALL Price (Black-Scholes)')
plt.title('Real vs. Calculated CALL Prices')
plt.xlabel('Index')
plt.ylabel('Price')
plt.legend()
plt.show()

# Plot real price vs. calculated price for PUTS
plt.figure(figsize=(12, 6))
plt.plot(results_df[results_df['type'] == 'put']['real_price'], label='Real PUT Price')
plt.plot(results_df[results_df['type'] == 'put']['bs_price'], label='Calculated PUT Price (Black-Scholes)')
plt.title('Real vs. Calculated PUT Prices')
plt.xlabel('Index')
plt.ylabel('Price')
plt.legend()
plt.show()

spot_price = stock_price

# Plot Error vs. Strike Price CALLS
plt.figure(figsize=(12, 6))
plt.plot(results_df[results_df['type'] == 'call']['strike'], results_df[results_df['type'] == 'call']['error'], label='Error', marker='o')

# Shading for ITM, ATM, OTM
plt.axvspan(24300, spot_price - 100, color='green', alpha=0.2, label='In the Money (ITM)')
plt.axvspan(spot_price - 100, spot_price + 100, color='yellow', alpha=0.3, label='At the Money (ATM)')
plt.axvspan(spot_price + 100, 25800, color='red', alpha=0.2, label='Out of the Money (OTM)')

# Set the x-axis limits from 24,300 to 25,800
plt.xlim(24000, 25800)

# Add labels and title
plt.xlabel('Strike Price')
plt.ylabel('Error')
plt.title('Error vs. Strike Price CALL')
plt.legend()
plt.show()

# Plot Error vs. Strike Price PUTS
plt.figure(figsize=(12, 6))
plt.plot(results_df[results_df['type'] == 'put']['strike'], results_df[results_df['type'] == 'put']['error'], label='Error', marker='o')

# Shading for ITM, ATM, OTM
plt.axvspan(24300, spot_price - 100, color='green', alpha=0.2, label='Out of the Money (OTM)')
plt.axvspan(spot_price - 100, spot_price + 100, color='yellow', alpha=0.3, label='At the Money (ATM)')
plt.axvspan(spot_price + 100, 25800, color='red', alpha=0.2, label='In the Money (ITM)')

# Set the x-axis limits from 24,300 to 25,800
plt.xlim(24000, 25800)

# Add labels and title
plt.xlabel('Strike Price')
plt.ylabel('Error')
plt.title('Error vs. Strike Price PUT')
plt.legend()
plt.show()